author: AVM
name: linting
description: Tests the example supplied in the input. Needs checkout and Azure login prior.
inputs:
  github-token:
    description: The GitHub token
    required: true

runs:
  using: composite
  steps:

    - name: terraform fmt check
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:avm-latest make tffmtcheck

    - name: terraform validate
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src -e ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000 mcr.microsoft.com/azterraform:avm-latest make tfvalidatecheck

    - name: terrafmt check
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:avm-latest make terrafmtcheck

    - name: tflint
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src -e ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000 mcr.microsoft.com/azterraform:avm-latest make tflint

    - name: tfsec
      shell: bash
      run: |
        echo "Bypass tfsec for now"
