author: AVM
name: linting
description: Tests the example supplied in the input. Needs checkout and Azure login prior.
inputs:
  github-token:
    description: The GitHub token
    required: true

runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ">=1.5.0"

    - name: terraform init
      run: terraform init
      shell: bash

    - name: terraform validate
      run: terraform validate
      shell: bash

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: v0.48.0
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: get tflint config
      run: |
        curl --header "Authorization: Bearer ${{ inputs.github-token }}" https://raw.githubusercontent.com/Azure/terraform-azurerm-avm-template/main/.tflint.hcl -o .tflint.hcl
      shell: bash

    - name: tflint init
      run: tflint --init
      shell: bash

    - name: tflint
      run: tflint
      shell: bash
