author: AVM
name: linting
description: Tests the example supplied in the input. Needs checkout and Azure login prior.
inputs:
  github-token:
    description: The GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: grept
      run: exit 0
      shell: bash

    - name: terraform fmt check
      run: exit 0
      shell: bash

    - name: terraform validate
      run: exit 0
      shell: bash

    - name: terraform docs check
      run: exit 0
      shell: bash

    - name: tflint
      run: exit 0
      shell: bash

    - name: tfsec
      run: exit 0
      shell: bash
