author: AVM
name: linting
description: Tests the example supplied in the input. Needs checkout and Azure login prior.
inputs:
  github-token:
    description: The GitHub token
    required: true

runs:
  using: composite
  steps:

    - name: terraform fmt check
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform make tffmtcheck

    - name: terraform validate
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src -e ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000 mcr.microsoft.com/azterraform make tfvalidatecheck

    - name: terrafmt check
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform make terrafmtcheck

    - name: tflint
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src -e ARM_SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000 mcr.microsoft.com/azterraform make tflint

    - name: mapotf-precommit check
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform make mapotf-precommit-check

    - name: grept-precommit check
      shell: bash
      run: |
        docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform make grept-precommit-check

    - name: tfsec
      shell: bash
      run: |
        echo "Bypass tfsec for now"
