#!/usr/bin/env bash

usage () {
  echo "Usage: avm <make target>"
}

if [ ! $(command -v docker) ]; then
    echo "Error: Docker is not installed. Please install docker first."
    exit 1
fi

if [ -z "$1" ]; then
    echo "Error: Please provide a make target. See https://github.com/Azure/tfmod-scaffold/blob/main/avmmakefile for available targets."
    echo
    usage
    exit 1
fi

docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform make "$1"
