author: AVM
name: e2e - getexamples
description: Gets example directories from `examples/` and outputs them to the next step
inputs:
  github-token:
    description: The GitHub token to use for the API calls
    required: true
outputs:
  examples:
    description: The examples to test
    value: ${{ steps.getexamples.outputs.examples }}
runs:
  using: composite
  steps:
    - name: get examples
      id: getexamples
      run: |
        # Get all the folders in the examples directory
        $folders = Get-ChildItem -Directory

        $examples = @()
        $e2eTests = @()

        foreach ($folder in $folders) {
            # Check if the folder contains at least one .tf file
            $files = Get-ChildItem -Path $folder.FullName -File -Filter "*.tf"
            if($files.Count -ne 0) {
                $examples += $folder.Name

                # Check if the folder contains a .e2eignore file
                $ignore = Get-ChildItem -Path $folder.FullName -File -Filter ".e2eignore"
                if($ignore.Count -eq 0) {
                    $e2eTests += $folder.Name
                }
            }
        }

        if($examples.Count -eq 0) {
          throw "At least one example must be present for Azure Verified Modules"
        }

        $e2eTestsJson = ConvertTo-Json $e2eTests

        Write-Output "examples=$e2eTestsJson" >> $env:GITHUB_OUTPUT

      working-directory: examples
      shell: pwsh
