author: AVM
name: e2e - getexamples
description: Gets example directories from `examples/` and outputs them to the next step
inputs:
  github-token:
    description: The GitHub token to use for the API calls
    required: true
outputs:
  examples:
    description: The examples to test
    value: ${{ steps.getexamples.outputs.examples }}
runs:
  using: composite
  steps:
    - name: get examples
      id: getexamples
      run: |
        # ls -d */                        = list directories
        # cut -d/ -f1                     = strip trailing slash from ls output
        # jq -R -s -c 'split("\n")[:-1]') = creates JSON array:
        #                                    -R treats the input as string instead of JSON
        #                                    -s joins all lines into an array
        #                                    -c creates a compact output
        #                                    [:-1] removes the last empty string in the output array
        DIRS="$(ls -d */ | cut -d/ -f1 | jq -R -s -c 'split("\n")[:-1]')"
        # Set output
        echo examples="$DIRS" >> "$GITHUB_OUTPUT"
      working-directory: examples
      shell: bash
