author: AVM
name: e2e - getexamples
description: Gets example directories from `examples/` and outputs them to the next step
inputs:
  github-token:
    description: The GitHub token to use for the API calls
    required: true
outputs:
  examples:
    description: The examples to test
    value: ${{ steps.getexamples.outputs.examples }}
runs:
  using: composite
  steps:
    - name: get examples
      id: getexamples
      run: |
        # Get latest release from GitHub API and get download URL for the Linux x64 binary
        URL=$(curl -sL -H "Authorization: Bearer ${{ inputs.github-token }}" https://api.github.com/repos/matt-FFFFFF/jsonls/releases/latest \
          | jq -r '.assets[] | select( .name | test("linux_amd64")) | .browser_download_url')

        # Download the binary and extract
        curl -sL "$URL" | tar -xvz jsonls

        # Ensure exec bit set
        sudo chmod a+x jsonls

        # Move binary to path
        sudo mv jsonls /usr/local/bin/jsonls

        # Get the examples
        echo examples="$(jsonls -d)" >> "$GITHUB_OUTPUT"
      working-directory: examples
      shell: bash
