author: AVM
name: Module version check
description: Checks that module version has been updated on PR
inputs:
  version-file-name:
    description: Terraform JSON file containing module version
    required: false
    default: locals.version.tf.json
  jq-query:
    description: jq query to extract module version
    required: false
    default: .locals.module_version
  github_token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
    - name: semver regex
      shell: bash
      run: |
        echo "Skip version check as we are migrating to new modtm provider"
